Iris_Not_Scale_KNN = "result/Iris/KNN_Not_Scale.txt"
Iris_Scale_KNN = "result/Iris/KNN_Scale.txt"
Iris_Not_Scale_NB = "../result/Iris/NB_Not_Scale.txt"
Iris_Scale_NB = "../result/Iris/NB_Scale.txt"
Iris_Not_Scale_SVM = "../result/Iris/SVM_Not_Scale.txt"
Iris_Scale_SVM = "../result/Iris/SVM_Scale.txt"
Iris_Not_Scale_NN = "../result/Iris/NN_Not_Scale.txt"
Iris_Scale_NN = "../result/Iris/NN_Scale.txt"

# car
Car_Not_Scale_KNN = "../result/car/KNN_Not_Scale.txt"
Car_Scale_KNN = "../result/car/KNN_Scale.txt"
Car_Not_Scale_NB = "../result/car/NB_Not_Scale.txt"
Car_Scale_NB = "../result/car/NB_Scale.txt"
Car_Not_Scale_SVM = "../result/car/SVM_Not_Scale.txt"
Car_Scale_SVM = "../result/car/SVM_Scale.txt"
Car_Not_Scale_NN = "../result/car/NN_Not_Scale.txt"
Car_Scale_NN = "../result/car/NN_Scale.txt"